services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ProductCatalog
      POSTGRES_DB: ProductCatalogDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  pgdata:
  mongo_data:
